---
- name: Deploy KDE Workstation
  hosts: test-kitchen
  become: true

  pre_tasks:
    # Add kdeconfig ansible module
    - name: Pre task setup
      ansible.builtin.dnf:
        name:
          - ansible-collection-community-general

  roles:
    - repos
    - install
